/**
 * CAMADA JOGO. Textos da UI com i18n PT/EN funcional.
 *
 * `T` é um proxy que devolve a string do idioma ATIVO, então todos os call sites
 * (`T.continuar`, etc.) continuam iguais e passam a refletir o idioma em runtime.
 * `setLanguage()` troca o idioma e notifica os ouvintes (telas se re-renderizam).
 * EN é tipado como Record das chaves de PT: o compilador garante PARIDADE de chaves
 * (falta/sobra de chave entre idiomas vira erro de build). Ver docs/tecnica-i18n.md.
 */
export type Lang = "pt" | "en";

const PT = {
  title: "Brasa",
  subtitle: "A última chama no fundo do poço",
  menuVerso: "Enquanto a Brasa arder, o frio não vence.",
  continuar: "Continuar",
  novoJogo: "Novo Jogo",
  carregar: "Carregar",
  opcoes: "Opções",
  voltar: "Voltar",
  retomar: "Retomar",
  salvarAgora: "Salvar agora",
  sairTitulo: "Sair para o título",
  pausado: "Pausado",
  menu: "Menu",
  semSaves: "Nenhum jogo salvo ainda.",
  importar: "Importar save",
  apagar: "Apagar",
  exportar: "Exportar",
  audio: "Áudio",
  geral: "Geral",
  musica: "Música",
  efeitos: "Efeitos",
  idioma: "Idioma",
  autosalvando: "Salvando...",
  capitulo: "Capítulo",
  pontos: "Pontos",
  objetivo: "Objetivo",
  perfil: "Perfil",
  mapa: "Mapa",
  verMapa: "Ver mapa",
  nome: "Nome",
  salvar: "Salvar",
  salvo: "Salvo",
  tempoDeJogo: "Tempo de jogo",
  progresso: "Progresso",
  membroDesde: "Membro desde",
  voceEstaAqui: "Você está aqui",
  fechar: "Fechar",
  mapaTitulo: "Mapa da Descida",
  conquistas: "Conquistas",
  conquistaDesbloqueada: "Conquista desbloqueada",
  bloqueada: "Bloqueada",
  salvarCarregar: "Salvar / Carregar",
  novoSave: "Novo save",
  sobrescrever: "Sobrescrever",
  automatico: "Automático",
  manual: "Manual",
  confirmar: "Confirmar",
  cancelar: "Cancelar",
  erro: "Erro",
  apagarTitulo: "Apagar save?",
  apagarMsg: "Esta ação não pode ser desfeita.",
  sairConfirmaTitulo: "Sair para o título?",
  sairMsg: "O progresso é salvo automaticamente, mas você voltará ao menu principal.",
  acessibilidade: "Acessibilidade",
  escalaInterface: "Escala da interface",
  reduzirMovimento: "Reduzir movimento",
  altoContraste: "Alto contraste",
  audioEmBreve: "Os controles de áudio terão efeito quando o som for implementado.",
  // Crônica (Codex)
  cronica: "Crônica",
  cronicaSubtitulo: "Personagens, lugares e relatos revelados na jornada.",
  registroOculto: "Registro ainda não revelado.",
  arrasteParaGirar: "Arraste para girar",
  catPersonagens: "Personagens",
  catLugares: "Lugares",
  catRelatos: "Relatos",
  // Diário (registro de objetivos)
  diario: "Diário",
  diarioTitulo: "Diário da Descida",
  emAndamento: "Em andamento",
  concluidos: "Concluídos",
  nenhumObjetivo: "Nenhum objetivo ativo.",
  // Opções: gráficos / diálogo / controles
  graficos: "Gráficos",
  qualidade: "Qualidade",
  qualBaixo: "Baixo",
  qualMedio: "Médio",
  qualAlto: "Alto",
  dialogo: "Diálogo",
  velocidadeTexto: "Velocidade do texto",
  velLento: "Lento",
  velNormal: "Normal",
  velRapido: "Rápido",
  velInstantaneo: "Instantâneo",
  dialogoEmBreve: "Terá efeito quando as caixas de diálogo forem implementadas.",
  controles: "Controles",
  remapear: "Remapear",
  pressioneTecla: "Pressione uma tecla...",
  restaurarPadrao: "Restaurar padrão",
  acFrente: "Avançar",
  acTras: "Recuar",
  acEsq: "Esquerda",
  acDir: "Direita",
  acCorrer: "Correr",
  acPular: "Pular",
  acAtaque: "Ataque leve",
  acPesado: "Ataque pesado",
  acEsquiva: "Esquiva",
  acBloqueio: "Bloqueio",
  acFagulha: "Golpe de fogo (fagulha)",
  acLockon: "Mirar (lock-on)",
  // Criação de personagem (Nova Descida)
  novaJornada: "Nova Descida",
  novaJornadaSub: "Acenda a fagulha e desça ao poço.",
  nomeHeroi: "Nome da Acendedora",
  corDoManto: "Cor do manto",
  domInicial: "Dom inicial",
  dom: "Dom",
  dificuldade: "Dificuldade",
  comecar: "Iniciar a descida",
} as const;

export type StringKey = keyof typeof PT;

const EN: Record<StringKey, string> = {
  title: "Brasa",
  subtitle: "The last flame at the bottom of the pit",
  menuVerso: "While the Brasa burns, the cold does not win.",
  continuar: "Continue",
  novoJogo: "New Game",
  carregar: "Load",
  opcoes: "Options",
  voltar: "Back",
  retomar: "Resume",
  salvarAgora: "Save now",
  sairTitulo: "Quit to title",
  pausado: "Paused",
  menu: "Menu",
  semSaves: "No saved games yet.",
  importar: "Import save",
  apagar: "Delete",
  exportar: "Export",
  audio: "Audio",
  geral: "Master",
  musica: "Music",
  efeitos: "Effects",
  idioma: "Language",
  autosalvando: "Saving...",
  capitulo: "Chapter",
  pontos: "Points",
  objetivo: "Objective",
  perfil: "Profile",
  mapa: "Map",
  verMapa: "View map",
  nome: "Name",
  salvar: "Save",
  salvo: "Saved",
  tempoDeJogo: "Playtime",
  progresso: "Progress",
  membroDesde: "Member since",
  voceEstaAqui: "You are here",
  fechar: "Close",
  mapaTitulo: "Map of the Descent",
  conquistas: "Achievements",
  conquistaDesbloqueada: "Achievement unlocked",
  bloqueada: "Locked",
  salvarCarregar: "Save / Load",
  novoSave: "New save",
  sobrescrever: "Overwrite",
  automatico: "Automatic",
  manual: "Manual",
  confirmar: "Confirm",
  cancelar: "Cancel",
  erro: "Error",
  apagarTitulo: "Delete save?",
  apagarMsg: "This action cannot be undone.",
  sairConfirmaTitulo: "Quit to title?",
  sairMsg: "Progress is saved automatically, but you will return to the main menu.",
  acessibilidade: "Accessibility",
  escalaInterface: "Interface scale",
  reduzirMovimento: "Reduce motion",
  altoContraste: "High contrast",
  audioEmBreve: "Audio controls will take effect once sound is implemented.",
  cronica: "Chronicle",
  cronicaSubtitulo: "Characters, places and accounts revealed along the journey.",
  registroOculto: "Entry not yet revealed.",
  arrasteParaGirar: "Drag to rotate",
  catPersonagens: "Characters",
  catLugares: "Places",
  catRelatos: "Accounts",
  diario: "Journal",
  diarioTitulo: "Journal of the Descent",
  emAndamento: "In progress",
  concluidos: "Completed",
  nenhumObjetivo: "No active objective.",
  graficos: "Graphics",
  qualidade: "Quality",
  qualBaixo: "Low",
  qualMedio: "Medium",
  qualAlto: "High",
  dialogo: "Dialogue",
  velocidadeTexto: "Text speed",
  velLento: "Slow",
  velNormal: "Normal",
  velRapido: "Fast",
  velInstantaneo: "Instant",
  dialogoEmBreve: "Takes effect once dialogue boxes are implemented.",
  controles: "Controls",
  remapear: "Rebind",
  pressioneTecla: "Press a key...",
  restaurarPadrao: "Restore defaults",
  acFrente: "Move forward",
  acTras: "Move back",
  acEsq: "Strafe left",
  acDir: "Strafe right",
  acCorrer: "Run",
  acPular: "Jump",
  acAtaque: "Light attack",
  acPesado: "Heavy attack",
  acEsquiva: "Dodge",
  acBloqueio: "Block",
  acFagulha: "Ember strike (spark)",
  acLockon: "Lock-on",
  novaJornada: "New Descent",
  novaJornadaSub: "Light the spark and descend into the pit.",
  nomeHeroi: "Lamplighter's name",
  corDoManto: "Cloak color",
  domInicial: "Calling",
  dom: "Calling",
  dificuldade: "Difficulty",
  comecar: "Begin the descent",
};

let current: Lang = "pt";
const listeners = new Set<() => void>();

export function getLanguage(): Lang {
  return current;
}

export function setLanguage(lang: Lang): void {
  if (lang === current) return;
  current = lang;
  if (typeof document !== "undefined") document.documentElement.lang = lang;
  for (const cb of listeners) cb();
}

/** Inscreve para reagir à troca de idioma; retorna função para cancelar. */
export function onLanguageChange(cb: () => void): () => void {
  listeners.add(cb);
  return () => listeners.delete(cb);
}

export const T = new Proxy({} as Record<StringKey, string>, {
  get(_t, key) {
    const k = key as StringKey;
    return (current === "en" ? EN : PT)[k] ?? PT[k];
  },
}) as Record<StringKey, string>;
